--- #main file
#  - name: apply common configuration to all nodes 
#    hosts: all
#    user: test
#    sudo: yes
#    connection: ssh
#    gather_facts: yes
#    roles:
#      - common
  


- name: configure database server
  hosts: DataBaseServer
  user: test
  sudo: yes
  connection: ssh
  gather_facts: yes

  roles: 
    - db

