---
 - name: install mariadb
   yum: name={{ item }} state=installed
   with_items:
    - mariadb-server
    - MySQL-python
  
 - name: install libsemanage-python
   yum: name=libsemanage-python state=installed 


 - name: Configure SELinux to start mysql on any port
   seboolean: name=mysql_connect_any state=true persistent=yes
  
 - name: create configuration file
   template: src=my.cnf.j2 dst=/etc/my.cnf
   notify: 
     - restart mariadb  
   
 - name: start mariadb
   service: name=mariadb state=started enabled=yes
   
 - name: adding firewalld rule
   firewalld: port={{ mysql_port }}/tcp permanent=true state=enabled

 - name: create aplication database
   mysql_db: name={{ dbname }} state=present
   
 - name: create user for database
   mysql_user: name={{ dbuser }} password={{ upassword }} priv='*.*:ALL' host='%' state=present