---
 - name: upgrade all packages
   yum: name='*' state=latest 
   
 - name: install mysql package
   yum: name={{ item }} state=installed
   with_items:
    - mysql-server
    - Mysql-python
    - libsellinux-python
    - libsemanager-python
  
 - name: configure SELinux to run on any port
   seboolean: name=mysql_connect_any state=true persistent=yes
   when: sestatus.rc != 0
   
 - name: config file create
   template: src=my.cnf.j2 dest=/etc/my.cnf
   notify: 
      - restart mysql
 
 - name: Strart mysql service
   service: name=mysqld state=started enabled=yes

 - name: insert iptables rule
   lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}" 
               insertafter="^:OUTPUT " line="-A INPUT -p tcp --dport {{mysql_port}} -j ACCEPT" 
   notify: restart iptables
   
 - name: create applicateion database
   mysql_db: name={{ dbname }} state=present

 - name: create application dbuser
   mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*ALL host='%' state=present
