---
#  - name: import pgp key from mysql reposytory
#    rpm_key: key={{ item }} state=present
#    with_items:
#     - "http://repo.mysql.com/RPM-GPG-KEY-mysql"

#  - name: install mysql reposytory
#    command: "rpm -Uhv --force {{ item.href }} creates={{ item.creates }}" 
#    with_items:
#     - {
#       href: "http://repo.mysql.com/mysql-community-release-el7.rpm",
#       creates: "/etc/yum.repos.d/mysql.repo"
#     }

#  - name: install mysql reposytory
#    yum_repository:
#     name: mysql
#     description: mysql server reposytory 
#     gpgkey: http://repo.mysql.com/RPM-GPG-KEY-mysql
#     baseurl: http://repo.mysql.com/mysql-community-release-el7.noarch.rpm
#     gpgcheck: yes
#     enabled: yes

#  - name: upgrade all packages
#    yum: name='*' state=latest 
#    register: status



#  - name: install mysql package
#    yum: name={{ item }} state=installed
#    with_items:
#     - mysql-server
#     - Mysql-python
#     - libsellinux-python
#     - libsemanager-python
  
#  - name: configure SELinux to run on any port
#    seboolean: name=mysql_connect_any state=true persistent=yes
#    when: sestatus.rc != 0
   
#  - name: config file create
#    template: src=my.cnf.j2 dest=/etc/my.cnf
#    notify: 
#       - restart mysql
 
#  - name: Strart mysql service
#    service: name=mysqld state=started enabled=yes

#  - name: insert iptables rule
#    lineinfile: dest=/etc/sysconfig/iptables state=present regexp="{{ mysql_port }}" 
#                insertafter="^:OUTPUT " line="-A INPUT -p tcp --dport {{mysql_port}} -j ACCEPT" 
#    notify: restart iptables
   
#  - name: create applicateion database
#    mysql_db: name={{ dbname }} state=present

#  - name: create application dbuser
#    mysql_user: name={{ dbuser }} password={{ upassword }} priv=*.*ALL host='%' state=present


  - name: check if installed
    command: yum list | grep mysql-community-release | awk '{print $3}'
    register: result
  - debug: msg="{{ result.stdout_lines.find('installed')!=-1"}}


# - name: download mysql repo
#   get_url:
#     url: http://repo.mysql.com/mysql-community-release-el7.rpm
#     dest: /tmp/
#   when: 

# - name: install mysql repo
#   command: /usr/bin/rpm -ivh /tmp/mysql-community-release-el7.rpm

# - name: upgrade all packages
#   yum: name='*' state=latest update_cache=yes
  #run_once: true


# - name: install mysql package
#   yum: name={{ item }} state=installed
#   with_items:
#    - mysql-server
#    - Mysql-python
#    - libsellinux-python
#    - libsemanager-python