---
 - hosts: all
   tasks:
     - name: installing eple and gpg keys
       rpm_key: "key={{ item }} state=present"
       with_items:
        - "https://fedoraproject.org/static/0608B895.txt"
        - "http://rpms.famillecollet.com/RPM-GPG-KEY-remi"
  
     - name: installing eple and remy repo
       command: "rpm -Uhv --force {{ item.href }} creates={{item.creates}}"
       with_items:
        - {
          
        }     
        
